version: '3.4'

services:

  todolistwebapi:
    image: ${DOCKER_REGISTRY-}todolistwebapi
    build:
      context: .
      dockerfile: ToDoListWebAPI\Dockerfile
    platform: windows
    ports:
     - "5133:80"
    depends_on:
      - mssql-server
    


  todolistwebinfrastructure:
    image: ${DOCKER_REGISTRY-}todolistwebinfrastructure
    build:
      context: .
      dockerfile: ToDoListWebInfrastructure\Dockerfile
    platform: windows
    ports:
     - "8080:80"
    depends_on:
      - mssql-server

  todolistwebservices:
    image: ${DOCKER_REGISTRY-}todolistwebservices
    build:
      context: .
      dockerfile: ToDoListWebInfrastructure\ToDoListWebServices
    platform: windows
    ports:
     - "7212:80"
    depends_on:
      - mssql-server

  todolistwebui:
    image: ${DOCKER_REGISTRY-}todolistwebui
    build:
      context: .
      dockerfile: ToDoListWebInfrastructure\ToListWebUI
    platform: windows
    ports:
     - "44339:80"
    depends_on:
      - mssql-server



  mssql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Express
      MSSQL_SA_PASSWORD: YourPassword
      MSSQL_USER: User
      MSSQL_PASSWORD: ""
    ports:
      - "1433:1433"
