version: '3.8'

services:
  app:
    image: todolistweb:dev
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
